# Change these first
owner: DianaHaidarbaigi # Your GitHub organization or username, where this repository lives
repo: LuisenGym # The name of this repository

sites:
  - name: Luinet
   url: https://luinet.de
  - name: Halloluise
    url: https://halloluise.de
  - name: eduPort Lui
    url: https://luise.hamburg.de
  - name: LMS Hamburg
    url: https://lms.lernen.hamburg
 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /LuisenGym
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Luisen-Gymnasium Bergedorf
  introTitle: "Status der Webseiten und Dienste des Luisen-Gymnasiums Bergedorf"
  introMessage: Hier werden die einzelnen Zustände der genutzen Diesnte und Websiten angezeigt
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /LuisenGym
    - title: Halloluise
      href: https://halloluise.de
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
