# Change these first
owner: DianaHaidarbaigi # Your GitHub organization or username, where this repository lives
repo: LuisenGym # The name of this repository

sites:
  - name: Luinet
    url: https://luinet.de
    maxResponseTime: 1000
    icon: https://halloluise.de/wp-content/uploads/2017/09/cropped-luilogo-1-150x150.png
    assignees: # Users to assign downtime issues (optional)
    - DianaHaidarbaigi
    - aruben
  - name: Halloluise
    url: https://halloluise.de
    maxResponseTime: 1000
    icon: https://halloluise.de/wp-content/uploads/2017/09/cropped-luilogo-1-150x150.png
    assignees: # Users to assign downtime issues (optional)
    - DianaHaidarbaigi
    - aruben
  - name: eduPort Lui
    url: https://luise.hamburg.de
    maxResponseTime: 3000
    icon: https://eduport.hamburg.de/wp-content/uploads/sites/223/2016/04/cropped-icon-1-32x32.jpg
    assignees: # Users to assign downtime issues (optional)
    - DianaHaidarbaigi
    - aruben
  - name: LMS Hamburg
    url: https://lms.lernen.hamburg
    maxResponseTime: 3000
    icon: https://lms.lernen.hamburg/theme/image.php/ocschool/theme/1616487992/favicon
    assignees: # Users to assign downtime issues (optional)
    - DianaHaidarbaigi
    - aruben
  - name: Divis
    url: https://login-divis.hamburg.de/logon/LogonPoint/tmindex.html
    maxResponseTime: 3000
    icon: https://schul-it.hamburg.de/contentblob/2011400/980d81807b9464f255c2d1a628b2f322/thumbnail/headernavigation-fm.png
    assignees: # Users to assign downtime issues (optional)
    - DianaHaidarbaigi
    - aruben
   
 
 # CI schedule
workflowSchedule:
  graphs: "0 0,12,18 * * *"
  responseTime: "*/10 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /LuisenGym
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Luisen-Gymnasium Bergedorf
  introTitle: "Status der Webseiten und Dienste des Luisen-Gymnasiums Bergedorf"
  introMessage: Hier werden die einzelnen Zustände der genutzen Diesnte und Websiten angezeigt
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /LuisenGym
    - title: Halloluise
      href: https://halloluise.de
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
